INFO (theano.gof.compilelock): Waiting for existing lock by unknown process (I am process '37888')
INFO (theano.gof.compilelock): To manually release the lock, delete /home/jb6504/.theano/compiledir_Linux-3.10-el7.x86_64-x86_64-with-centos-7.3.1611-Core-x86_64-2.7.12-64/lock_dir
11.03.2018 04:12:48 INFO    Hi! How are you today?
11.03.2018 04:12:48 INFO    Startup options:
11.03.2018 04:12:48 INFO      Algorithm:                     truth
11.03.2018 04:12:48 INFO      Point by point:                False
11.03.2018 04:12:48 INFO      Morphing-aware mode:           False
11.03.2018 04:12:48 INFO      Smeared data:                  False
11.03.2018 04:12:48 INFO      Training sample:               baseline
11.03.2018 04:12:48 INFO      alpha:                         None
11.03.2018 04:12:48 INFO      Histogram / AFC X indices:     [1, 38, 39, 40, 41]
11.03.2018 04:12:48 INFO      AFC epsilon:                   None
11.03.2018 04:12:48 INFO      Neyman construction toys:      True
11.03.2018 04:12:48 INFO      Other options:                 
11.03.2018 04:12:48 INFO      Base directory:                /home/jb6504/higgs_inference
11.03.2018 04:12:48 INFO      ML-based strategies available: False
11.03.2018 04:12:48 INFO    Starting truth calculation
11.03.2018 04:12:48 DEBUG    NC settings: False neyman 36 10000 1001
11.03.2018 04:12:53 INFO    Starting evaluation
11.03.2018 04:12:55 INFO    Starting roaming
11.03.2018 04:15:20 INFO    Calculating cross-entropy on train set
11.03.2018 04:15:21 INFO    Training cross-entropy: 0.657932534292
11.03.2018 04:15:21 INFO    Starting evaluation of Neyman experiments
Traceback (most recent call last):
  File "experiments.py", line 106, in <module>
    options=args.options)
  File "/home/jb6504/higgs_inference/higgs_inference/strategies/truth.py", line 137, in truth_inference
    llr_neyman_null = -2. * np.sum(np.log(r_neyman_null[1]), axis=2)
  File "/share/apps/python/2.7.12/intel/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/fromnumeric.py", line 1848, in sum
    out=out, **kwargs)
  File "/share/apps/python/2.7.12/intel/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/_methods.py", line 32, in _sum
    return umr_sum(a, axis, dtype, out, keepdims)
ValueError: 'axis' entry is out of bounds
